//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2013 uniCenta
//    http://www.unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.config;

import com.openbravo.data.user.DirtyManager;
import com.openbravo.pos.forms.AppConfig;
import java.awt.Component;
import javax.swing.SpinnerNumberModel;


public class JPanelPointCardSetup extends javax.swing.JPanel implements PanelConfig {
    
    private DirtyManager dirty = new DirtyManager();
    private String receipt="1";
    private Integer x = 0;
    private String receiptSize;
    private String pickupSize;
    private Integer ps = 0;


    public JPanelPointCardSetup() {
        initComponents();
        jTextMoneyToPoint.getDocument().addDocumentListener(dirty);
    }
    
    
    @Override
    public boolean hasChanged() {
        return dirty.isDirty();
    }
    
    @Override
    public Component getConfigComponent() {
        return this;
    }
   
    @Override
    public void loadProperties(AppConfig config) {
        jTextMoneyToPoint.setText(config.getProperty("till.moneytopoint"));               
    }
   
    @Override
    public void saveProperties(AppConfig config) {
        
        config.setProperty("till.moneytopoint", jTextMoneyToPoint.getText());
        dirty.setDirty(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextMoneyToPoint = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), bundle.getString("label.configreceipt"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.setLayout(null);

        jTextMoneyToPoint.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextMoneyToPoint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextMoneyToPoint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextMoneyToPointKeyReleased(evt);
            }
        });
        jPanel1.add(jTextMoneyToPoint);
        jTextMoneyToPoint.setBounds(150, 20, 150, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText(bundle.getString("Label.moneytopoint")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 130, 40);

        add(jPanel1);
        jPanel1.setBounds(10, 10, 730, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMoneyToPointKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMoneyToPointKeyReleased

    }//GEN-LAST:event_jTextMoneyToPointKeyReleased
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextMoneyToPoint;
    // End of variables declaration//GEN-END:variables
    
}
